// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2QjWh5R6qdDaYg-xH16DWHwzriWFi3M',
    appId: '1:543200092966:web:3ed88bdb232dd4086f57e7',
    messagingSenderId: '543200092966',
    projectId: 'quickchat-babe9',
    authDomain: 'quickchat-babe9.firebaseapp.com',
    storageBucket: 'quickchat-babe9.appspot.com',
    measurementId: 'G-0N697M1JEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5EdFctCVlxjrDydb4tVyp_a0HNpYW4v4',
    appId: '1:543200092966:android:0456dfb075809f0e6f57e7',
    messagingSenderId: '543200092966',
    projectId: 'quickchat-babe9',
    storageBucket: 'quickchat-babe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAt4CtFKG64yxbuUdmt5BEiP8lNF9ERI',
    appId: '1:543200092966:ios:1f91f3d91273c7566f57e7',
    messagingSenderId: '543200092966',
    projectId: 'quickchat-babe9',
    storageBucket: 'quickchat-babe9.appspot.com',
    iosBundleId: 'com.example.quickchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAt4CtFKG64yxbuUdmt5BEiP8lNF9ERI',
    appId: '1:543200092966:ios:1f91f3d91273c7566f57e7',
    messagingSenderId: '543200092966',
    projectId: 'quickchat-babe9',
    storageBucket: 'quickchat-babe9.appspot.com',
    iosBundleId: 'com.example.quickchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl2QjWh5R6qdDaYg-xH16DWHwzriWFi3M',
    appId: '1:543200092966:web:cc3234c229f99a206f57e7',
    messagingSenderId: '543200092966',
    projectId: 'quickchat-babe9',
    authDomain: 'quickchat-babe9.firebaseapp.com',
    storageBucket: 'quickchat-babe9.appspot.com',
    measurementId: 'G-9F8BCGPXF3',
  );

}